global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'mops'
    metrics_path: "/prometheus"
    static_configs:
      - targets: ['host.docker.internal:8090', 'host.docker.internal:8091', 'host.docker.internal:8092']