version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: ${MONGO_CONTAINER_NAME:-mongodb}
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER:-mongouser}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-mongopass}
    ports:
      - ${MONGO_PORT:-27017}:${MONGO_PORT:-27017}
    volumes:
      - mongodb:/mongodb 
      
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER:-mongouser}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD:-mongopass}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN:-mongoexpress}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD:-mongoexpresspass}
      - ME_CONFIG_MONGODB_SERVER=${MONGO_CONTAINER_NAME:-mongodb}
      - ME_CONFIG_MONGODB_PORT=${MONGO_PORT:-27017}
    ports:
      - 8081:8081
    volumes:
      - mongo_express:/mongo_express  

volumes:
  mongodb:
  mongo_express: